### ISSUE TITLE
OstSdk.initialize() should be call before get in android

### ISSUE THREAD

**Issue by AshokL123** [ostdotcom/ost-wallet-sdk-react-native#125]
![Screenshot 2020-01-25 at 1 43 00 PM](https://user-images.githubusercontent.com/53734919/73118322-9b28f700-3f78-11ea-9d96-986ea272bf47.png)

same code working in iOS but not in android

**Comment by rachinkapoor** [comment]
@AshokL123 ,
Yes, the error is correct. 
The sdk needs to be initialized so that it can create proper tables and run migrations as needed.

However, we are willing to further look into the issue.
Could you kindly provide us with code-snippet?

**Comment by rachinkapoor** [comment]
@AshokL123 , kindly provide more issue if your are still facing the issue.
