### ISSUE TITLE
Token Holder is either logging out or already logged out.

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#126]
I have try to clear all ost session 

OstWalletSdk.logoutAllSessions(
      userId,
      this.workflowCallback
)

but sdk Interrupt the flow and say

{
    "api_error": {
        "code": "UNPROCESSABLE_ENTITY",
        "error_data": [],
        "internal_id": "a_s_s_mo_l_4",
        "msg": "Token Holder is either logging out or already logged out."
    },
    "error_code": "API_RESPONSE_ERROR",
    "error_info": {
        "err": {
            "code": "UNPROCESSABLE_ENTITY",
            "error_data": [Array
            ],
            "internal_id": "a_s_s_mo_l_4",
            "msg": "Token Holder is either logging out or already logged out."
        },
        "success": false
    },
    "error_message": "Token Holder is either logging out or already logged out.",
    "internal_error_code": "UNPROCESSABLE_ENTITY",
    "is_api_error": true
}

**Comment by rachinkapoor** [comment]
Hi @Speed-stack ,
Thanks for reporting the issue.
This error means that one of the following scenarios has occurred:
- User doesn't have any authorized sessions.
- `logoutAllSessions` is already in progress. 
  * This could be an indicator that the `logoutAllSessions` is being called twice.
