### ISSUE TITLE
OstWalletSdk.activateUser() Spending limit provided is invalid. Spending limit should be in atto BT and can not be decimal value. Please inspect the value being sent is correct and not null, rectify and re-submit

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#127]
{
    "error_code": "INVALID_SESSION_SPENDING_LIMIT",
    "error_message": "Spending limit provided is invalid. Spending limit should be in atto BT and can not be decimal value. Please inspect the value being sent is correct and not null, rectify and re-submit.",
    "internal_error_code": "w_au_vp_2",
    "is_api_error": false
}

**Comment by rachinkapoor** [comment]
@Speed-stack ,
Thanks for reporting the issue.
**Questions**
* Do you get this error while activating the user or while authorizing the session?
* I request you to kindly provide the code-snippet for the issue.
