### ISSUE TITLE
Spending limit provided is invalid.

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#128]
{"error_code": "INVALID_SESSION_SPENDING_LIMIT", "error_message": "Spending limit provided is invalid. Spending limit should be in atto BT and can not be decimal value. Please inspect the value being sent is correct and not null, rectify and re-submit.", "internal_error_code": "w_au_vp_2", "is_api_error": false}

**Comment by rachinkapoor** [comment]
@Speed-stack ,
Thanks for reporting the issue. 
Could you kindly provide the code-snippet for activating user?

**Comment by Speed-stack** [comment]
I've activating a user while I get this error

activateUser() {
    this.workflowCallback.flowInterrupt = (ostWorkflowContext, ostError) => {
      this.flowInterrupedCallback(ostWorkflowContext, ostError);
    };
    this.workflowCallback.flowComplete = (ostWorkflowContext, ostContextEntity) => {
      this.flowCompleteCallback(ostWorkflowContext, ostContextEntity);
    };
    const { userId, userPin, passphrasePrefix, spendingLimit, expireAfterInSecs } = this.request;

    OstWalletSdk.activateUser(
      userId,
      userPin,
      passphrasePrefix,
      spendingLimit,
      expireAfterInSecs,
      this.workflowCallback
    )
  }

my spending limit is
const spendingLimit = "1000000000000000000000000";

**Comment by rachinkapoor** [comment]
As per above code, spendingLimit and expireAfterInSecs are incorrectly passed.

Please try below code:
```
OstWalletSdk.activateUser( userId, 
              userPin, 
              passphrasePrefix, 
              expireAfterInSecs, 
              spendingLimit, 
                this.workflowCallback)
```

**Documentation:**
https://github.com/ostdotcom/ost-wallet-sdk-react-native/blob/develop/documentation/OstCoreWorkflows.md#activateuser

Additionally, I would also suggest you use `OstWalletUI. activateUser`.
Using OstWalletUI would save your effort required build all the UI for Sdk integration.

For even faster integration, I would recommend following the quick-start guide (Starting version 2.3.12). To experience the different flows implemented using the quick-start guide, you could checkout the [react-native-demo-app](https://github.com/ostdotcom/react-native-demo-app). And [react-native-demo-app](https://github.com/ostdotcom/react-native-demo-app) will also server as code reference and save you some time.

I request you to kindly confirm if the fix provided works for you.
If not, we shall be happy to dig further into it.

Cheers!
-r

**Comment by rachinkapoor** [comment]
Hi @Speed-stack ,
Could you kindly confirm if the issue was resolved or further assistance is needed.

**Comment by AshokL123** [comment]
@rachinkapoor  Thanks, it's working
