### ISSUE TITLE
iOS 13 Unable to recognize the device.

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#129]
In iOS 13 device deviceRegistered callback say 

{
    "error_code": "DEVICE_NOT_SETUP",
    "error_message": "Unable to recognize the device. Please setup this device for the user using workflows provided at; https://dev.ost.com/platform/docs/sdk",
    "internal_error_code": "n_ad_gcd_2",
    "is_api_error": false
}

but in iOS 11.1 it working fine

**Comment by rachinkapoor** [comment]
@Speed-stack , thanks for reporting the issue.
However, this is a known issue. 
The keychain is broken in iOS 13 simulators and hence the sdk is unable to store/retrieve keys from keychain.
 
I request you try it on an actual device and confirm the same.

**Comment by Speed-stack** [comment]
it's working in actual device
