### ISSUE TITLE
Android TrustKit was initialized with a different network policy than the one configured in the App's manifest

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#130]
{"error_code": "UNCAUGHT_EXCEPTION_HANDELED", "error_message": "TrustKit was initialized with a different network policy than the one configured in the App's manifest.", "internal_error_code": "rn_ownsm_i_1", "is_api_error": 0}

**Comment by rachinkapoor** [comment]
Hi @Speed-stack ,
Thanks for reporting the issue.
If your application also uses trustkit, I request follow steps provided

If not, I am guessing you are trying to test your application with debug build on a device/simulator with Api-28 or above.
Unfortunately, to get around this issue you need to implement the TrustKit for your application.
The detailed explanation is provided [here](https://github.com/ostdotcom/ost-wallet-sdk-react-native/blob/develop/documentation/android_setup.md#debug-builds-with-android-9-api-level-28).

**Comment by Speed-stack** [comment]
@rachinkapoor  Thanks, It's working now...
