### ISSUE TITLE
creating new session alway loading 

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#131]

**Comment by Speed-stack** [comment]
![IMG_0047](https://user-images.githubusercontent.com/54949248/73638374-4714c580-4690-11ea-87c5-6e008c2a0a8b.PNG)

**Comment by rachinkapoor** [comment]
@Speed-stack could you please update the ticket with appropriate description?

**Comment by Speed-stack** [comment]
![IMG_0048](https://user-images.githubusercontent.com/54949248/73649922-e0e76d00-46a6-11ea-8f07-d35d3a4f901a.PNG)

**Comment by rachinkapoor** [comment]
:)

Could you give me code snippet?

If you are using Wallet Settings UI component, we will need the following 2 code snippets:
1. Code to navigate to wallet settings component.
2. Code of delegate passed to the wallet settings component.

If you are directly using the create session UI workflow, we will need the following 2 code snippets:
1. Code of delegate passed to the UI workflow
2. Code invoking the UI workflow.

**Comment by Speed-stack** [comment]
it's working now
