### ISSUE TITLE
executeTransaction nothing happen 

### ISSUE THREAD

**Issue by Speed-stack** [ostdotcom/ost-wallet-sdk-react-native#141]
I have trying to executeTransaction but nothing happen. sdk can't return completed or Interruped response 

`export function executeTransaction(userId, tokenHolderAddresses, amounts, transactionType, meta) {
    return (dispatch) => {

        let workflowCallback = new OstWalletWorkFlowCallback();
        workflowCallback.flowComplete = (workflowContext, contextEntity) => {
            console.log("flowComplete");
            console.log("workflowContext: ", workflowContext.WORKFLOW_TYPE);
            console.log("executeTransaction: ", contextEntity);
            dispatch(getBalance());

        };
        workflowCallback.flowInterruped = (workflowContext, { error }) => {
            console.log("flowInterruped");
            console.log("workflowContext: ", workflowContext.WORKFLOW_TYPE);
            console.log("error: ", error);
        };
        OstWalletSdk.executeTransaction(
            userId,
            tokenHolderAddresses,
            amounts,
            transactionType,
            meta,
            workflowCallback
        )
    }
}`

**Comment by AshokL123** [comment]
I'm having the same issue

**Comment by rachinkapoor** [comment]
Hi @Speed-stack ,
As per my initial analysis, the workflow is being interrupted.  
Could you try changing:
`workflowCallback.flowInterruped = (workflowContext, { error }) => {`
to:
`workflowCallback. flowInterrupt = (workflowContext, { error }) => {`

Link to documentation:
https://github.com/ostdotcom/ost-wallet-sdk-react-native/blob/develop/documentation/OstCoreWorkflows.md#an-example-of-callback-implementation

**Comment by Speed-stack** [comment]
@rachinkapoor   it's working 

but got some other error 

{
    "error_code": "RULES_NOT_FOUND",
    "error_message": "Unable to recognize the Rule Name. Please inspect a valid rule name is passed. Ensure its not null and re-submit the request. Visit https://dev.ost.com/platform to know about rule details",
    "internal_error_code": "rn_owrs_et_4",
    "is_api_error": false
}

can you help me with it?

**Comment by rachinkapoor** [comment]
Rule Name can be one of the following:
1. Direct Transfer
2. Pricer

**Comment by rachinkapoor** [comment]
I think you need to use `Direct Transfer`.

**Comment by rachinkapoor** [comment]
@Speed-stack ,
I would also suggest you look at `OstTransactionHelper` if you are using `direct transfer`.

https://github.com/ostdotcom/ost-wallet-sdk-react-native/blob/develop/documentation/OstTransactionHelper.md

The helper automatically triggers add session workflow if no session key present to perform the required transaction.

**Comment by daan-ost** [comment]
Yes we only use `Direct Transfer`

**Comment by Speed-stack** [comment]
still return bug 

{"error_code": "SESSION_NOT_FOUND", "error_message": "The device doesn't has any active session. Please authorize a session before doing any transaction. Workflow details provided at https://dev.ost.com/platform/docs/sdk/references", "internal_error_code": "w_et_pfdt_1", "is_api_error": false}

**Comment by Speed-stack** [comment]
it's fixed
